name: Pipeline

on:
  push:
  pull_request:


jobs:
  test:
    name: test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '18'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Execute Gradle test
        run: ./gradlew test
